name: payment-guard
channels:
  - defaults
dependencies:
  - ipykernel
  - python=3.12
  - sqlite
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pytest
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - statsmodels
  - altair
  - plotly
  - streamlit
